#!/usr/bin/env bash

for d in auto-complete breadcrumb haskell-mode haskell-mode-exts itimer-el magit; do
    d=$d.git
    (cd emacs/${d} && git remote set-url origin git@github.com:pheaver/$d)
done


