#!/bin/sh

rm -f TAGS
if [ `which hasktags` >/dev/null ]; then
    /usr/bin/find . -iname \*.\*hs | xargs hasktags -e
    mv TAGS TAGS.haskell
    chmod -x TAGS.haskell
    chmod a+r TAGS.haskell
else
    echo "hasktags not installed, skipping" >&2
fi

if [ `which etags` >/dev/null ]; then
    etags -R . ||
    (/usr/bin/find . -iname \*.\*el | xargs etags &&
     /usr/bin/find . -iname \*.\*sh | xargs etags -a)
else
    echo "etags not installed, skipping" >&2
fi
