#!/bin/sh

git co public &&
(for i in `git rev-list --reverse placeholder..master`; do
    git cherry-pick $i || exit 1
done) &&
git tag -d placeholder &&
git tag placeholder master &&
echo done || echo something failed

git co master
