#!/bin/sh

# this will take new commit in public and put them in master
git branch temp public &&
git rebase --onto merged master temp &&
git co master &&
git merge --ff-only temp &&
echo done || echo something failed
git branch -D temp

